services:
    _defaults:
        public: true

    Oro\Bundle\CalendarBundle\Controller\CalendarController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\CalendarBundle\Controller\Dashboard\DashboardController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
