assets:
    css:
        'orocalendar':
            - 'bundles/orocalendar/css/scss/main.scss'
            - 'bundles/orocalendar/css/scss/print.scss'
            - 'bundles/bowerassets/fullcalendar/dist/fullcalendar.css'
