assets:
    css:
        'orocalendar':
            - 'bundles/orocalendar/css/less/main.scss'
            - 'bundles/orocalendar/css/less/print.scss'
            - 'bundles/bowerassets/fullcalendar/dist/fullcalendar.css'
