placeholders:
    placeholders:
        oro_reminder_reminder_templates:
            items:
                calendar_event_reminder_template: ~
    items:
        calendar_event_reminder_template:
            template: '@@OroCalendar/CalendarEvent/reminderTemplate.html.twig'

        oro_add_calendar_event_button:
            template: '@@OroCalendar/CalendarEvent/activityButton.html.twig'
            acl: oro_calendar_event_create

        oro_assign_calendar_event_button:
            template: '@@OroCalendar/CalendarEvent/assignCalendarEventButton.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\UserBundle\Entity\User)'
            acl: oro_calendar_event_create

        oro_add_calendar_event_link:
            template: '@@OroCalendar/CalendarEvent/activityLink.html.twig'
            acl: oro_calendar_event_create

        oro_assign_calendar_event_link:
            template: '@@OroCalendar/CalendarEvent/assignCalendarEventLink.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\UserBundle\Entity\User)'
            acl: oro_calendar_event_create
